# Generated by Django 3.2.9 on 2021-11-30 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='classe',
            old_name='nomClasse',
            new_name='nom_classe',
        ),
    ]
