# Generated by Django 3.2.9 on 2021-12-14 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('departement', '0002_rename_nomclasse_classe_nom_classe'),
    ]

    operations = [
        migrations.AlterField(
            model_name='departement',
            name='nom',
            field=models.CharField(blank=True, choices=[('GEM', 'Gem'), ('GC', 'Gc'), ('TC', 'Tc'), ('AERO', 'Aero'), ('GIT', 'Git')], max_length=100),
        ),
    ]
